### ISSUE TITLE
Feature Request: Automatically return BoxList if response contains a list.

### ISSUE THREAD

**Issue by mitchos** [SteveMcGrath/restfly#2]
### What is happening
When Box is enabled, all responses with a JSON content-type are assumed to be a `dict`. This causes an exception from box when an API returns a `list` with content-type JSON:
> box.exceptions.BoxError: json data not returned as a dictionary, but rather a list

We can overcome this by specifying `box=BoxList` when sending the request from the APIEndpoint method. This can be slightly onerous as we need to import `BoxList` into our APIEndpoint modules and then specify `box=BoxList` for every method that we expect a list from. 

Some API responses can return content-type JSON as either a `dict` or `list`, which requires us to test for that and have a conditional return.

### What would be nice
If Restfly could automatically return a `Box` for `dict` or `BoxList` for `list`.

### Idea for implementation:
Modify session.py
https://github.com/SteveMcGrath/restfly/blob/c899d89b90aa7da2c1c01e239126e7df4b59619f/restfly/session.py#L575-L585

Modified session.py
``` python
                    if box and 'application/json' in ctype:
                        # we want to make a quick check to ensure that there is
                        # actually some data to pass to Box.  If there isn't,
                        # then we should just return back a None response.
                        if len(resp.text) > 0:
                            if box_attrs.get('default_box'):
                                self._log.debug(
                                    'unknown attrs will return as %s' %
                                    box_attrs.get('default_box_attr', Box)
                                )
                            try:
                                return box.from_json(resp.text, **box_attrs)
                            except BoxError:
                                return BoxList(json.loads(resp.text))
```

Let me know what you think?

**Comment by SteveMcGrath** [comment]
I'd like to do some testing first, it would also mean the need to pass the box attribute could instead be distilled to a simple boolean value.

My concern is the amount of processing time spend on a more complex document.  It might make more sense to simply convert the JSON response into native datatypes, check the instance, and return the correct object.

**Comment by mitchos** [comment]
Sure thing, my first attempt at this I used `literal_eval()` from `ast` to convert and perform the type check. This obviously added an additional import and more lines of code. 

EAFP looked a bit simpler but I admit the example I provided assumes we'll get a `dict` or a `list` and not some other structure.

`BoxList` will accept any `str` and create a `BoxList` out of it, so this could certainly produce some undesired results. I agree that the datatype checks are probably the best way forward.


``` python
from box import BoxList

my_str = "This is not cool"

print(BoxList(my_str))

>>> ['T', 'h', 'i', 's', ' ', 'i', 's', ' ', 'n', 'o', 't', ' ', 'c', 'o', 'o', 'l']
```

Thanks again for taking a look at this, much appreciated.

**Comment by SteveMcGrath** [comment]
So it's funny that you brought this up, as I was independently looking into a way to solve for this before you opened the issue.  Feel free to take a look at that solution and see if that works for you.

**Comment by mitchos** [comment]
Oh this is awesome! :smile: 

This is really going to help simplify a lot of my request methods. Thank you so much, this is exactly the functionality I was looking for.

**Comment by SteveMcGrath** [comment]
glad to hear it solves the need.  I think your [pyZscaler](https://github.com/mitchos/pyZscaler/) project is the first one to use RESTfly outside of a lot of my own musings.  Great to see that it's useful ;)
