### ISSUE TITLE
Support user-supplied hooks for customized logging, progress tracking, etc..

### ISSUE THREAD

**Issue by mzpqnxow** [SteveMcGrath/restfly#3]
hey @SteveMcGrath you may remember be from over @ https://github.com/tenable/pyTenable

I sent in [this PR](https://github.com/tenable/pyTenable/pull/332) which was very useful to me in tracking the progress of very large downloads. I stumbled across RestFLY after seeing your response to a separate pyTenable issue and thought I might mention this here in case you found it to be worthwhile. It would be nice if you made inserting hooks at various layers easy, for things like tracking the progress of a page iterator, or a download/upload stream

In some cases of course this is just a matter of designing the class so that it's easy for the user to instrument the iteration; in some other cases it's a more low-level thing, like the PR above, where the `iter_content()` of the `requests.Response` object was handled directly by the hook

I haven't looked much at RestFLY yet, but I'm now pretty familiar with the iterators in pyTenable and see it's very similar. I wish I had come across your project about 2 years ago as I ended up writing something very similar- though admittedly a bit uglier, and with a nasty case of creeping featurism

Please feel free to close this out after reading it. I'm not sure if it will be interesting to you or not

EDIT: I also ended up implementing a `class ParallelExportsIterator(APIResultsIterator)` to parallelize downloading chunks from certain exports endpoints. That one is very ugly but it works. Just another idea on how you might want to extend RestFLY, or keep in mind how others may want to extend it while you're developing it

**Comment by SteveMcGrath** [comment]
TBH When i refactored the exports iterator in pytenable, I also made it to support threading.  The original PR in pyTenable makes sense, however I’m not sure of the best approach to support it in this library, as it’s mostly just about making the low-level bits of pytenable more generic for general consumption.  More recently we even switched my tenable to use this library for the low-level logic as well, mostly to reduce the amount of duplicated code as well.

I’m open to ideas as to where and how you’d like to use such a feature.

**Comment by mzpqnxow** [comment]
> TBH When i refactored the exports iterator in pytenable, I also made it to support threading

That's good to hear. Mine is very bad, I found the interface difficult to understand and not so easy to cleanly mold into this- I ended up needing to override more than one method iirc, which is usually a sign that it wasn't designed with that in mind, or I just failed to really understand the class operation. Maybe some amount of each :)

> The original PR in pyTenable makes sense, however I’m not sure of the best approach to support it in this library, as it’s mostly just about making the low-level bits of pytenable more generic for general consumption

Understood, the idea as I described it may not be the best fit and may fall outside of the scope of its functionality. I very briefly reviewed the code (literally ~15 minutes) but have not actually used it at this point, so I don't have a great feel right now about where it may make sense. 

> More recently we even switched my tenable to use this library for the low-level logic as well, mostly to reduce the amount of duplicated code as well.

That's great, pyTenable works very well for me (save some minor issues) but I'm sure you'll agree it's very, very painful to work on at times- a lot of redundant code and the like. My other complaint about pyTenable is the use of single-quotes for docstrings, but I don't think that's a substantive complaint :)

I'm happy to hear you're switching over to restFLY under the hood. The few PRs I sent were relatively simple adds but took much longer than usual to implement because the code was difficult to read which made it difficult to figure out the most appropriate way to implement the change(s). I have to commend the test suites though, very thorough

> I’m open to ideas as to where and how you’d like to use such a feature.

I'll try to see if I can make use of RestFLY in one of my projects some time soon so I have a better chance of spotting an opportunit

Thanks!

**Comment by SteveMcGrath** [comment]
> My other complaint about pyTenable is the use of single-quotes for docstrings, but I don't think that's a substantive complaint :)

PEP 257 does say to use triple double quotes here, so you're complaint on this is valid.  I never bothered to dig into it before.
